### ISSUE TITLE
wmts failing to load

### ISSUE THREAD

**Issue by rduivenvoorde** [geopython/MetaSearch#15]
When trying to load a wmts I get the following error:

![screenshot from 2014-02-14 18 07 46](https://f.cloud.github.com/assets/731673/2172957/9bb41832-959a-11e3-9855-575b4419f607.png)

To reproduce: use 'Nationaal Georegister (Nederland)" as CSW
Search for WMTS, and select for example: 
TOP250raster WMTS 
from the results

**Comment by tomkralidis** [comment]
Fixed in cadcdc9e5c6936dad6fb9d492fef56ac4e2f0ef6
