### ISSUE TITLE
connection dropdowns not synced

### ISSUE THREAD

**Issue by rduivenvoorde** [geopython/MetaSearch#17]
Removing a connection in the Services tab does not update the connection dropdown in the Search tab. So removing a connection (in the Services tab)  which in Search tab is the active one (or is still available) results in a Python error.

Editing the connection dropdown in the Services tab should sync immidiatly with the dropdown in the Search tab. Even better would be to reuse that widget...

**Comment by tomkralidis** [comment]
Fixed in 21677391149243a5e03d2bed72d774bbdd318e1b
