### ISSUE TITLE
after a python error the waiting cursor keeps being active

### ISSUE THREAD

**Issue by rduivenvoorde** [geopython/MetaSearch#18]
IF we have a python error (should not happen, but.... a lot of wrong metadata can do wrong...). the waiting cursor is active AND keeps active even after closing the MetaSearch dialog.

We could always put the default cursor back after closing our dialog?

**Comment by tomkralidis** [comment]
OK, let's add `QApplication.restoreOverrideCursor` when this happens, or is there another way?

**Comment by tomkralidis** [comment]
I've refactored things a bit as most (if not all) Python errors happen via OWSLib interactions. We shouldn't see raw Python errors at this point.
