### ISSUE TITLE
Couldn't load plugin MetaSearch due to an error when calling its classFactory() method

### ISSUE THREAD

**Issue by archaeogeek** [geopython/MetaSearch#2]
Just cloned the MetaSearch plugin into my .qgis2/python/plugins directory on Linux Mint running python 2.7 (QGIS 2.0.1) I get the following traceback when loading QGIS:

Couldn't load plugin MetaSearch due an error when calling its classFactory() method

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 204, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/jo/.qgis2/python/plugins/MetaSearch/**init**.py", line 79, in classFactory
    from cswclient import CSWClientPlugin
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 453, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/jo/.qgis2/python/plugins/MetaSearch/cswclient.py", line 36, in 
    import cswclientdialog
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 453, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/jo/.qgis2/python/plugins/MetaSearch/cswclientdialog.py", line 50, in 
    from cswresponsedialog import CSWResponseDialog
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 453, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/jo/.qgis2/python/plugins/MetaSearch/cswresponsedialog.py", line 37, in 
    from ui.ui_cswresponsedialogbase import Ui_CSWResponseDialog
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 453, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named ui_cswresponsedialogbase

Python version:
2.7.3 (default, Sep 26 2013, 16:38:06) 
[GCC 4.7.2]

QGIS version:
2.0.1-Dufour Dufour, exported

Python path: ['/home/jo/.qgis2/python/plugins/MetaSearch', '/home/jo/.qgis2/python/plugins/QGIS-Gazetteer-Plugin', '/usr/share/qgis/python', '/home/jo/.qgis2/python', '/home/jo/.qgis2/python/plugins', '/usr/share/qgis/python/plugins', '/usr/local/lib/python2.7/dist-packages/dulwich-0.8.7-py2.7-linux-x86_64.egg', '/usr/local/lib/python2.7/dist-packages/hg_git-0.4.0-py2.7.egg', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-linux2', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PIL', '/usr/lib/python2.7/dist-packages/gst-0.10', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client', '/usr/lib/python2.7/dist-packages/ubuntuone-client', '/usr/lib/python2.7/dist-packages/ubuntuone-control-panel', '/usr/lib/python2.7/dist-packages/ubuntuone-couch', '/usr/lib/python2.7/dist-packages/ubuntuone-storage-protocol']

I guess that ImportError: No module named ui_cswresponsedialogbase is the important one.

Any thoughts?

Jo

**Comment by tomkralidis** [comment]
@archaeogeek this is part of our QGIS 2.0 upgrade (#1).  I'll have some time in January to tackle this fully. Any contributions/PRs are more than welcome.

**Comment by alexbruy** [comment]
@archaeogeek you only copied sources. Sources doesn't include compiled forms, you need to compile them by yourself. Also not, that plugin does not updated to QGIS 2.0, it works only under QGIS <= 1.8

**Comment by archaeogeek** [comment]
Hi,

I followed the instructions for install exactly from the readme.md so if they are wrong then I suggest that they need changing- there is no mention of compiling anything.

Jo

**Comment by tomkralidis** [comment]
thanks @alexbruy. @archaeogeek FYI I made a fix to `pavement.py` and updated `README.md` (dac7652).  Having said this, the plugin should be stable in the next couple of weeks.
