### ISSUE TITLE
Add WFS problem

### ISSUE THREAD

**Issue by ggiuliani** [geopython/MetaSearch#22]
An error message appears when I try to "Add WFS" resource (see the attached screenshot).
I've tested this functionality with the following metadata record:
http://metadata.grid.unep.ch:8080/geonetwork/srv/eng/main.home?uuid=2b5a8d12-2575-4371-be55-928c87a93e9b

![wfs_error](https://f.cloud.github.com/assets/6728425/2215952/733229c6-99ff-11e3-8ebf-b3196ca755ee.png)

**Comment by tomkralidis** [comment]
thanks @astroimagine. Fixed in 232332c66909cf74bd1360cb0e70eac27d1311d0
