### ISSUE TITLE
setup localization via Transifex

### ISSUE THREAD

**Issue by tomkralidis** [geopython/MetaSearch#3]
Applied to both plugin and docs.

**Comment by tomkralidis** [comment]
This is now setup (thanks @rduivenvoorde for debugging) at https://www.transifex.com/projects/p/MetaSearch.  Notes:
- @rduivenvoorde and @tomkralidis are maintainers initially
- we can add languages manually for now via the Transifex UI, and in the codebase
- we _should_ commit the .po / .ts files, but I haven't done so yet until #24 is implemented (this may change our UI / text some)
- `paver extract_messages` provides the bootstrap to get the initial strings for UI, UI templates and docs

Workflow:
- add new language via Transifex UI and in code dirs via git
- translators provide content to Transifex (either via UI or code via `tx push -s`)
- maintainers `tx pull -a`
- `paver compile_messages` builds all the .qm / .mo files
- `paver refresh_docs` builds all docs for all languages

**Comment by tomkralidis** [comment]
done.  Process:

```
# upload to Transifex
paver extract_messages`  # extract strings
tx push -s  # send en sources to Transifex
# build
`tx pull -a` # pull all languages from Transifex
paver compile_messages
paver refresh_docs
```

This results in a fully translated package to work against, package and upload.

@rduivenvoorde: the last outstanding item is docs/website.  `paver refresh_docs` will build docs in all languages.  `paver publish_docs` (don't try it yet) will publish the English docs as current (to http://geopython.github.io/MetaSearch/), and the other languages get published to `http://geopython.github.io/MetaSearch/<lang>`.

Is there another structure we should do to make things better? How does QGIS do it?  As well, we need a way to provide language selection in the docs.

**Comment by tomkralidis** [comment]
As well, foreach language, perhaps we can add the following steps to `publish_docs`:
- keep only one of `_static`, `_sources`, `_images` directories
- scan all Sphinx html outputs and point to one language's `_static`, `_sources`, `_images` directories
- delete all the others

**Comment by rduivenvoorde** [comment]
Hi Tom, with the QGIS sites we use sphinx-intl (https://pypi.python.org/pypi/sphinx-intl)

we only keep resources(=images etc) separated per language, where 'en' is the base-one and other can be copied over it. Sources are only en, and translations are only available as po files in i18n/locale dir. Themes are also not localized (some right to left magic via separate css file).

So in the build dir we first copy all english images (from resources/en so we have an english 'base'), and then we overwrite them with (optionally) available localized images (with exact the same name in resources/xx).

see https://github.com/qgis/QGIS-Website/blob/master/Makefile#L87-L114

**Comment by tomkralidis** [comment]
Done.  Website updated with multilingual docs/setup.
