### ISSUE TITLE
there is no hint to load default connections

### ISSUE THREAD

**Issue by rduivenvoorde** [geopython/MetaSearch#33]
after last update, all settings are changed, so I ended up as if I was a fresh user.

but because the other tabs were not working (only Services was active), I thought my plugin was frozen. Untill I thought about my settings and clicked 'Add default services'...

Should there not be a message somewhere, in case of showing of the plugin with zero connections, telling the user: "to start: either click default services, or create a new cws connection first". I know we do not like popups, but ...

**Comment by tomkralidis** [comment]
What if we test for this in startup and I there are no connections, then focus on the middle tab and set the text in the server info area with the hint to add default connections, etc.?

**Comment by rduivenvoorde** [comment]
Yep, good idea!

Which made me wonder: should we not also make 'help' button in the button bar on bottom of dialog?
Because then another option would be: no connection: open help in default browser exactly on the part where you describe that a connection is needed etc.

**Comment by tomkralidis** [comment]
FYI I've put in helper text for starters. Once we get this in docs then we can open in browser, good idea.
