### ISSUE TITLE
translate error at startup

### ISSUE THREAD

**Issue by rduivenvoorde** [geopython/MetaSearch#34]
![screenshot from 2014-02-24 08 22 24](https://f.cloud.github.com/assets/731673/2243262/c1f05704-9d24-11e3-95c6-dc5be8952589.png)

running here on a master version of QGIS of a couple of days old. Getting msg above. 
Is it working for others? 
Is the interface of 'translate' different between different QGIS versions?

**Comment by tomkralidis** [comment]
Thx.  Fixed in c1d2318
