### ISSUE TITLE
GetCapabilities response

### ISSUE THREAD

**Issue by ggiuliani** [geopython/MetaSearch#35]
When you have several services registered (2 in my case), this button does not refresh when switching from one service to another. You need to first click on the “ Service info” button so that it refreshes.

**Comment by tomkralidis** [comment]
Fixed in 6333d60f1afcd7bcc1edd5c3e87b1f75d0ebb503.  The 'GetCapabilities reponse' button will always be disabled when switching servers, so the user has to hit "Service Info" to ensure correct information.

**Comment by ggiuliani** [comment]
Thanks Tom.

Best

Greg

On 26 Feb 2014, at 14:33, Tom Kralidis notifications@github.com wrote:

> Fixed in 6333d60. The 'GetCapabilities reponse' button will always be disabled when switching servers, so the user has to hit "Service Info" to ensure correct information.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Dr. Gregory Giuliani
Scientific collaborator - Spatial Data Infrastructure
http://www.unige.ch/envirospace/People/giuliani.html

---

University of Geneva
Institute for Environmental Sciences/enviroSPACE
7 route de Drize, CH - 1227 CAROUGE
Phone: (+41 22) 379 07 09 Fax: (+41 22) 379 07 44
Web: http://www.unige.ch/envirospace
Email: gregory.giuliani@unige.ch

---

UNEP/DEWA/GRID-Geneva
International Environment House
11, chemin des Anémones, CH - 1219 CHATELAINE
Phone: (+41 22) 917 84 17 Fax: (+41 22) 917 80 29
Web: http://www.grid.unep.ch
Email: gregory.giuliani@unepgrid.ch

---
