### ISSUE TITLE
Add WFS and WCS problem with ISO19119

### ISSUE THREAD

**Issue by ggiuliani** [geopython/MetaSearch#36]
We were testing our services registry (based on GeoNetwork and ISO19119): http://services.grid.unep.ch:8080/geonetwork/srv/eng/csw?
We can add WMS/WMTS but WFS and WCS buttons never work. In metadata, standards are declared has OGC:WFS or OGC:WCS.

**Comment by tomkralidis** [comment]
@astroimagine thanks for the info.  FYI if I do a search on `wfs` on that CSW, and then click `View search results as XML`, none of the records have WFS or WCS links, so the metadata is missing.

**Comment by ggiuliani** [comment]
@tomkralidis Mmmh interesting :-) because the link are there if you look to a WFS metadata record in our GeoNetwork: http://services.grid.unep.ch:8080/geonetwork/srv/eng/metadata.show?id=49
So maybe this is a bug on GN or second option, the documentation of the WFS is wrong?
Sorry for having reported a wrong bug ;-)

**Comment by tomkralidis** [comment]
The plugin is looking for, in the DC representation of the record, the `dc:URI` or `dct:references` element, which is not present:

`http://services.grid.unep.ch:8080/geonetwork/srv/eng/csw?service=CSW&version=2.0.2&request=GetRecordById&id=0d3bb6ae-6ef7-4638-b5de-c36114787223&elementsetname=full`

**Comment by ggiuliani** [comment]
I've made some tests and it seems that's a problem coming from GeoNetwork. When I change the standard name (see screenshot) to OGC:WFS (instead of OGC:WMS) then the element dc:URI disappears in the XML document. 
![untitled](https://f.cloud.github.com/assets/6728425/2283340/116e78e4-9fbc-11e3-8f62-127c26fc646b.png)
