### ISSUE TITLE
Problem when using a proxy

### ISSUE THREAD

**Issue by pieterdg** [geopython/MetaSearch#37]
I installed the MetaSearch Catalogue Client plugin for QGIS and was able to test it and use it to interact with our CSW (and start optimizing our metadata).
(out CSW is this: https://www.dov.vlaanderen.be/geonetwork/srv/nl/csw?Request=GetCapabilities&Service=CSW&Version=2.0.2 ).

However I am faced with the problem that it is not possible to use the plugin when I have to activate a proxy to allow access to the internet (which I always have to do when I'm working at my office - Belgium - Flemish government).

Is it possible to make sure that the plugin can be used when the proxy is on ?

**Comment by rduivenvoorde** [comment]
@pieterdg I've been using the plugin in an environment where we were behind a proxy. My conclusion was that the plugin apparently uses the (normal) QGIS proxy values. Which you can set at General Options, Network settings.

Is the plugin manager getting it's information for you? Or is that also not able to connect? Are you able to connecto to WMS servers there?

**Comment by pieterdg** [comment]
The proxy settings are defined in the network settings panel:
![image001](https://f.cloud.github.com/assets/673227/2270223/fe027e50-9ee8-11e3-83db-ec7e34206fe7.png)

I can visualize WMS layers through the proxy, but not access the CSW.

**Comment by tomkralidis** [comment]
Fixed in 9c5ee7ed1c01c424ed3f9590185d38aaa2d96892
