### ISSUE TITLE
add UNEP/GRID-Europe GeoNetwork to default list

### ISSUE THREAD

**Issue by tomkralidis** [geopython/MetaSearch#39]
(cc @astroimagine) Proposed by UNEP/GRID:

http://geonetwork.grid.unep.ch:8080/geonetwork/srv/en/csw

**Comment by ggiuliani** [comment]
@tomkralidis Thanks a lot Tom.
We will change URL on April 2nd and it will be: http://metadata.grid.unep.ch:8080/geonetwork/srv/eng/csw?
the old (http://geonetwork.grid.unep.ch:8080) will be redirected to this new URL.

**Comment by tomkralidis** [comment]
Thanks @astroimagine.  Added in 2d77d1f in master, and will be part of next release.
