### ISSUE TITLE
Please support ISO servers

### ISSUE THREAD

**Issue by pcav** [geopython/MetaSearch#41]
INSPIRE CSW geoportal [0] only returns ISO, not Dublin Core. While this might be a mistake, it would be important for MetaSearch to support (and perhaps add in the standard distribution) it.

[0] http://inspire-geoportal.ec.europa.eu/GeoportalProxyWebServices/resources/OGCCSW202/AT?service=CSW

**Comment by tomkralidis** [comment]
As per #62 moved to http://hub.qgis.org/issues/11730
