### ISSUE TITLE
cannot import name bbox

### ISSUE THREAD

**Issue by gubuntu** [geopython/MetaSearch#42]
Cannot load metasearch in QGIS master, it give the error "cannot import name BBox"

**Comment by rduivenvoorde** [comment]
hi, thanks for opening this issue.
can you provide some more information.
myself I have QGIS master/2.3 running both on linux and on windows, and the latest MetaSearch plugin from the qgis repo is working fine with me

the BBox class should be in (on linux)
.qgis2/python/plugins/MetaSearch/ext-libs/owslib/fes.py

are you maybe running in a virtual python env?

anyway: plz provide some more info about versions and setup

**Comment by gubuntu** [comment]
On 21/03/2014 14:54, Richard Duivenvoorde wrote:

> hi, thanks for opening this issue.
> can you provide some more information.
> myself I have QGIS master/2.3 running both on linux and on windows, 
> and the latest MetaSearch plugin from the qgis repo is working fine 
> with me
> 
> the BBox class should be in (on linux)
> .qgis2/python/plugins/MetaSearch/ext-libs/owslib/fes.py
> 
> are you maybe running in a virtual python env?
> 
> anyway: plz provide some more info about versions and setup
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/geopython/MetaSearch/issues/42#issuecomment-38273095.
> 
> That class is there (line 338).

I'm not running a venv.

Couldn't load plugin MetaSearch due an error when calling its 
classFactory() method

Traceback (most recent call last):
   File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 204, in 
startPlugin
     plugins[packageName] = package.classFactory(iface)
   File "/home/gavin/.qgis2/python/plugins/MetaSearch/**init**.py", line 
35, in classFactory
     from MetaSearch.plugin import MetaSearchPlugin
   File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 453, in 
_import
     mod = _builtin_import(name, globals, locals, fromlist, level)
   File "/home/gavin/.qgis2/python/plugins/MetaSearch/plugin.py", line 
33, in
     from MetaSearch.dialogs.maindialog import MetaSearchDialog
   File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 453, in 
_import
     mod = _builtin_import(name, globals, locals, fromlist, level)
   File 
"/home/gavin/.qgis2/python/plugins/MetaSearch/dialogs/maindialog.py", 
line 44, in
     from owslib.fes import BBox, PropertyIsLike
ImportError: cannot import name BBox

QGIS version    2.3.0-Master    QGIS code revision    exported
Compiled against Qt    4.8.4    Running against Qt    4.8.4
Compiled against GDAL/OGR    1.9.0    Running against GDAL/OGR 1.9.0
Compiled against GEOS    3.3.3-CAPI-1.7.4    Running against GEOS 
3.3.8-CAPI-1.7.8
PostgreSQL Client Version    9.1.10    SpatiaLite Version 3.1.0-RC2
QWT Version    5.2.3    PROJ.4 Version    470

Ubuntu 13.10 64bit

## 

Gavin Fleming
t: 0218620670
w: 0218630660
c: 0845965680
f: 0866164820
Paarl
South Africa
18°59'19.6"E 33°44'46.1"S

**Comment by kalxas** [comment]
I saw similar issue yesterday and it was fixed by upgrading to latest OWSLib...

**Comment by gubuntu** [comment]
On 26/03/2014 12:48, Angelos Tzotsos wrote:

> I saw similar issue yesterday and it was fixed by upgrading to latest 
> OWSLib...
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/geopython/MetaSearch/issues/42#issuecomment-38669809.
> 
> I upgraded OWSLib from 0.5.1 to 0.8.6 and it did the trick, thanks

## 

Gavin Fleming
t: 0218620670
w: 0218630660
c: 0845965680
f: 0866164820
Paarl
South Africa
18°59'19.6"E 33°44'46.1"S
