### ISSUE TITLE
generate plugin documentation

### ISSUE THREAD

**Issue by tomkralidis** [geopython/MetaSearch#5]
cc @alexbruy 

FYI an initial sphinx setup is in `docs/` (FYI not sure how #3 is implicated).

**Comment by alexbruy** [comment]
Great! I'll try to find some free time on this weekend to work on docs, and maybe on code

**Comment by tomkralidis** [comment]
Partial update in b6df2091eb5c2755c0f327002807ced655628a9d.  Once the UI is finalized we can add screenshots.
