### ISSUE TITLE
entering on a search, makes you set extent to current bbox

### ISSUE THREAD

**Issue by rduivenvoorde** [geopython/MetaSearch#52]
in current version, if I enter a keyword to search for, and just press 'enter' (instead of clicking the 'search' button), the Xmax, Xmin, Ymax, Ymin is rewitten, to current bbox of the mapcanvas. Which when you start with an empty map is a bbox of zero meters/degrees, which makes a next search have zero results because of the (wrong) extent taken into account.

I've tried to look into the code what is triggering this, but only thing I could come up with is that the button 'Map extent' is silently activated/clicked because of the 'enter' action...

**Comment by tomkralidis** [comment]
@rduivenvoorde fixed in 2c81ce14142a322c932b6373bfaeb8a6acb5a693.  Can you verify?

**Comment by rduivenvoorde** [comment]
yep, ok now. Thanks. Should have found that myself :-)
