### ISSUE TITLE
MetaSearch dutch repo working in QGIS master + 2.4, but not in QGIS 2.6 ?

### ISSUE THREAD

**Issue by rduivenvoorde** [geopython/MetaSearch#69]
hi Tom,

strange error, while wanting to try metasearch in my own compiled QGIS2.6 (on Debian) on our 'nationaal georegister', I get the following error: 
Connection error: HTTP Error 401: Unauthorized

thinking there was something wrong with our service, i tried to connect using owslib in python... all working fine there..

Then i tried QGIS master, and that one was working, also tested 2.4 still working?

Can you please see if 2.6 is working for you?

I've tried to up/downgrade in different version:

QGIS master: OK
Installed version: 0.3.1 (in /home/richard/apps/qgis/master/debug/share/qgis/python/plugins/MetaSearch)
Available version: 0.3.2 (in QGIS Official Plugin Repository)

QGIS master: OK
Installed version: 0.3.2 (in /home/richard/.qgis2/python/plugins/MetaSearch)
Available version: 0.3.2 (in QGIS Official Plugin Repository)

QGIS 2.6: NOT OK: Connection error: HTTP Error 401: Unauthorized
Installed version: 0.3.2 (in /home/richard/.qgis2/python/plugins/MetaSearch)
Available version: 0.3.2 (in QGIS Official Plugin Repository)

QGIS 2.6: NOT OK: Connection error: HTTP Error 401: Unauthorized
Installed version: 0.3.1 (in /home/richard/apps/qgis/2.6/debug/share/qgis/python/plugins/MetaSearch)
Available version: 0.3.2 (in QGIS Official Plugin Repository)

Also testing QGIS 2.4: OK
Installed version: 0.2.0 (in /home/richard/apps/qgis/2.4/debug/share/qgis/python/plugins/MetaSearch)
Available version: 0.3.2 (in QGIS Official Plugin Repository)

Then upgrading the plugin in QGIS 2.4: OK
Installed version: 0.3.2 (in /home/richard/.qgis2/python/plugins/MetaSearch)
Available version: 0.3.2 (in QGIS Official Plugin Repository)

**Comment by tomkralidis** [comment]
Hi @rduivenvoorde this is due to the issue per https://github.com/geopython/MetaSearch/issues/68.  Solution and workarounds discussed there.  This has since been fixed in OWSLib (0.8.10), MetaSearch (0.3.2) and QGIS master and 2.6 branch.
