### ISSUE TITLE
CSW Meta Search has a problem working.

### ISSUE THREAD

**Issue by Terneuzen** [geopython/MetaSearch#71]
Dear Tom,

I reinstalled CSW 0.3.2 today, bud still get an error??

Er is een fout opgetreden bij het uitvoeren van Python code:

Traceback (most recent call last):
  File "C:/Users/Gebruiker/.qgis2/python/plugins\MetaSearch\dialogs\maindialog.py", line 471, in search
    self.display_results()
  File "C:/Users/Gebruiker/.qgis2/python/plugins\MetaSearch\dialogs\maindialog.py", line 483, in display_results
    's'[self.catalog.results['matches'] == 1:])
TypeError: not all arguments converted during string formatting

Python versie:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

QGIS versie:
2.6.1-Brighton Brighton, e2a51df

Python pad: ['C:/OSGEO4~1/apps/qgis/./python/plugins\processing', 'C:/OSGEO4~1/apps/qgis/./python', u'C:/Users/Gebruiker/.qgis2/python', u'C:/Users/Gebruiker/.qgis2/python/plugins', 'C:/OSGEO4~1/apps/qgis/./python/plugins', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg', 'c:\osgeo4~1\apps\python27\lib\site-packages\python_dateutil-2.1-py2.7.egg', 'c:\osgeo4~1\apps\python27\lib\site-packages\six-1.3.0-py2.7.egg', 'C:\OSGEO4~1\bin\python27.zip', 'C:\OSGEO4~1\apps\Python27\DLLs', 'C:\OSGEO4~1\apps\Python27\lib', 'C:\OSGEO4~1\apps\Python27\lib\plat-win', 'C:\OSGEO4~1\apps\Python27\lib\lib-tk', 'C:\OSGEO4~1\bin', 'C:\OSGEO4~1\apps\Python27', 'C:\OSGEO4~1\apps\Python27\lib\site-packages', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\PIL', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\win32', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\win32\lib', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\Pythonwin', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg', 'C:\Users\Gebruiker\.qgis2\python\plugins\geopunt4Qgis\ext-libs', 'C:\Users\Gebruiker\.qgis2\python\plugins\MetaSearch\ext-libs', 'C:\Users\Gebruiker\.qgis2\python\plugins\mmqgis/forms', 'C:\Users\Gebruiker\.qgis2\python\plugins\pdokbaggeocoder/forms', 'C:\OSGEO4~1\apps\qgis\python\plugins\fTools\tools']

**Comment by tomkralidis** [comment]
Thanks @Terneuzen for the report.  This is the same issue as #70, so I will close as duplicate.
