### ISSUE TITLE
MGRS plugin not working???

### ISSUE THREAD

**Issue by uranium87** [geopython/MetaSearch#72]
Hello I am trying to install an MGRS plugin to QGIS, from this source:
https://github.com/volaya/mgrs-tools

After some research, I figured the best way to install was to unzip into to the .qgis2/python/plugins folder. I also tried simply the .qgis2/python parent folder but neither have resulted in a correct installation. I am new to QGIS and this is my first plugin (aside from the core plugins that already are available) so I imagine I am doing something wrong. It shows up in the Plugins - Manage and Install Plugins window, but is red and reads "This plugin is broken: invalid syntax) in the view window to the right of the plugin list and gives the following error message when trying to activate the plugin:

Couldn't load plugin mgrs-tools-master due to an error when calling its classFactory() method

Traceback (most recent call last):
  File "C:/PROGRA~1/QGISWI~1/apps/qgis/./python\qgis\utils.py", line 219, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/Dave/.qgis2/python/plugins\mgrs-tools-master__init__.py", line 8, in classFactory
    from mgrstools import MGRSTools
  File "C:/PROGRA~1/QGISWI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Dave/.qgis2/python/plugins\mgrs-tools-master\mgrstools.py", line 3, in 
    import mgrs
  File "C:/PROGRA~1/QGISWI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\Dave.qgis2\python\plugins\mgrs-tools-master\ext-libs\mgrs__init__.py", line 1, in 
    from core import rt
  File "C:/PROGRA~1/QGISWI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\Dave.qgis2\python\plugins\mgrs-tools-master\ext-libs\mgrs\core.py", line 17, in 
    rt = ctypes.PyDLL(lib_path)
  File "C:\PROGRA~1\QGISWI~1\apps\Python27\lib\ctypes__init__.py", line 365, in **init**
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found

Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

QGIS version:
2.8.1-Wien Wien, exported

Python path: ['C:/PROGRA~1/QGISWI~1/apps/qgis/./python', u'C:/Users/Dave/.qgis2/python', u'C:/Users/Dave/.qgis2/python/plugins', 'C:/PROGRA~1/QGISWI~1/apps/qgis/./python/plugins', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg', 'C:\PROGRA~1\QGISWI~1\bin\python27.zip', 'C:\PROGRA~1\QGISWI~1\apps\Python27\DLLs', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\plat-win', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\lib-tk', 'C:\PROGRA~1\QGISWI~1\bin', 'C:\PROGRA~1\QGISWI~1\apps\Python27', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\PIL', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\win32', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\win32\lib', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\Pythonwin', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\six-1.3.0-py2.7.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg', u'C:/Users/Dave/.qgis2//python', 'C:\Users\Dave\.qgis2\python\plugins\mgrs-tools-master\ext-libs']

Any help you all can give is greatly appreciated!!

**Comment by tomkralidis** [comment]
FYI the MGRS issue tracker is at https://github.com/volaya/mgrs-tools/issues
