### ISSUE TITLE
Find services in the CSW and click on the link to add the service into the map using MetaSearch Catalogue Client plugin in QGIS

### ISSUE THREAD

**Issue by mfarook** [geopython/MetaSearch#73]
I am using Metasearch catalogue client qgis plugin(https://www.geodata.se/geonetwork/srv/eng/csw?service=CSW&request=GetCapabilities&version=2.0.2) to find services in csw and add the service into map.I had created a new service and searched using a keyword. It could see a list of services and datasets for the keyword which i had searched. But Add WMS/WMTS, Add WFS, WCS buttons are disabled. But i could see these buttons enabled for the default connections.What should be done to enable these buttons or how do these buttons gets enabled?The csw url is https://www.geodata.se/geonetwork/srv/eng/csw

![cswmetasearch](https://cloud.githubusercontent.com/assets/8999372/22196235/2b8b1656-e172-11e6-8a71-66f7f0e01783.png)

**Comment by tomkralidis** [comment]
FYI MetaSearch is now part of the core QGIS project.  The QGIS issue tracker is at http://hub.qgis.org/projects/quantum-gis/issues

Having said this, please post questions to the QGIS mailing list. QGIS issues are for software bugs/enhancements and related tasks.
