### ISSUE TITLE
implement template based display of UI results

### ISSUE THREAD

**Issue by tomkralidis** [geopython/MetaSearch#8]
implement template based display of server metadata and results metadata.

**Comment by rduivenvoorde** [comment]
@tomkralidis trying out the plugin. Having some issues with missing Templates:

TemplateNotFound: resources/templates/xml_highlight.html (when asking for GetCapabilitiesResponse for server)

TemplateNotFound: resources/templates/record_metadata.html (when asking for metadata of resultrecord)

But it seems you are halfway, so probably this was already on your radar :-)

**Comment by tomkralidis** [comment]
Thanks @rduivenvoorde this should be fixed now.
